"""Unit tests for the OpenAPI schema generated by FastAPI.

No database required — these tests inspect the schema object only.
All paths checked here are required by docs/backend-api-contract.md.
"""
from __future__ import annotations

import pytest

from app.main import create_app


@pytest.fixture(scope="module")
def schema() -> dict:
    return create_app().openapi()


@pytest.fixture(scope="module")
def paths(schema) -> dict:
    return schema["paths"]


@pytest.fixture(scope="module")
def components(schema) -> dict:
    return schema.get("components", {}).get("schemas", {})


# ── All required paths present ─────────────────────────────────────────────


_REQUIRED_PATHS = [
    "/api/v1/health",
    "/api/v1/health/ready",
    "/api/v1/users/me",
    "/api/v1/applications",
    "/api/v1/applications/{app_id}",
    "/api/v1/applications/{app_id}/status",
    "/api/v1/applications/{app_id}/comments",
    "/api/v1/applications/{app_id}/history",
    "/api/v1/activity/feed",
    "/api/v1/analytics/kpi",
]


@pytest.mark.parametrize("path", _REQUIRED_PATHS)
def test_required_path_present(paths, path):
    assert path in paths, f"Path missing from OpenAPI schema: {path}"


# ── HTTP methods per endpoint ──────────────────────────────────────────────


def test_health_has_get(paths):
    assert "get" in paths["/api/v1/health"]


def test_health_ready_has_get(paths):
    assert "get" in paths["/api/v1/health/ready"]


def test_users_me_has_get_and_patch(paths):
    assert "get" in paths["/api/v1/users/me"]
    assert "patch" in paths["/api/v1/users/me"]


def test_applications_has_get_and_post(paths):
    assert "get" in paths["/api/v1/applications"]
    assert "post" in paths["/api/v1/applications"]


def test_application_detail_has_get_patch_delete(paths):
    detail = paths["/api/v1/applications/{app_id}"]
    assert "get" in detail
    assert "patch" in detail
    assert "delete" in detail


def test_application_status_has_post_only(paths):
    ops = paths["/api/v1/applications/{app_id}/status"]
    assert "post" in ops
    assert "get" not in ops


def test_application_comments_has_post_only(paths):
    ops = paths["/api/v1/applications/{app_id}/comments"]
    assert "post" in ops
    assert "get" not in ops


def test_application_history_has_get_only(paths):
    ops = paths["/api/v1/applications/{app_id}/history"]
    assert "get" in ops
    assert "post" not in ops


def test_activity_feed_has_get(paths):
    assert "get" in paths["/api/v1/activity/feed"]


def test_analytics_kpi_has_get(paths):
    assert "get" in paths["/api/v1/analytics/kpi"]


# ── CommentRequest schema ──────────────────────────────────────────────────


def test_comment_request_schema_exists(components):
    assert "CommentRequest" in components


def test_comment_request_uses_text_not_comment(components):
    """Contract: body field is 'text'. Sending 'comment' must fail (extra=forbid)."""
    props = components["CommentRequest"].get("properties", {})
    assert "text" in props, "CommentRequest must have 'text' property"
    assert "comment" not in props, "CommentRequest must NOT have 'comment' property"


def test_comment_request_text_is_required(components):
    required = components["CommentRequest"].get("required", [])
    assert "text" in required


def test_comment_request_rejects_extra_fields(components):
    assert components["CommentRequest"].get("additionalProperties") is False


# ── StatusTransitionRequest schema ─────────────────────────────────────────


def test_status_transition_request_schema_exists(components):
    assert "StatusTransitionRequest" in components


def test_status_transition_request_uses_to_status(components):
    props = components["StatusTransitionRequest"].get("properties", {})
    assert "to_status" in props


def test_status_transition_to_status_is_required(components):
    required = components["StatusTransitionRequest"].get("required", [])
    assert "to_status" in required


def test_status_transition_to_status_is_enum(components):
    prop = components["StatusTransitionRequest"]["properties"]["to_status"]
    assert "enum" in prop
    enum_values = prop["enum"]
    for expected in ("SAVED", "APPLIED", "INTERVIEW_1", "OFFER", "REJECTED"):
        assert expected in enum_values


def test_status_transition_rejects_extra_fields(components):
    assert components["StatusTransitionRequest"].get("additionalProperties") is False


def test_status_transition_has_comment_and_correlation_id(components):
    """Both optional fields are present — they are stored in history."""
    props = components["StatusTransitionRequest"].get("properties", {})
    assert "comment" in props
    assert "correlation_id" in props


# ── ApplicationCreate schema ───────────────────────────────────────────────


def test_application_create_schema_exists(components):
    assert "ApplicationCreate" in components


def test_application_create_requires_company_name_and_role_title(components):
    required = components["ApplicationCreate"].get("required", [])
    assert "company_name" in required
    assert "role_title" in required


def test_application_create_rejects_extra_fields(components):
    assert components["ApplicationCreate"].get("additionalProperties") is False


# ── Response shapes present ────────────────────────────────────────────────


def test_application_read_schema_exists(components):
    assert "ApplicationRead" in components


def test_user_read_schema_exists(components):
    assert "UserRead" in components


def test_history_list_response_schema_exists(components):
    assert "HistoryListResponse" in components


def test_activity_feed_response_schema_exists(components):
    assert "ActivityFeedResponse" in components


def test_kpi_response_schema_exists(components):
    assert "KpiResponse" in components


# ── OpenAPI metadata ───────────────────────────────────────────────────────


def test_openapi_title(schema):
    assert schema["info"]["title"] == "job-tracker-api"


def test_openapi_version_present(schema):
    assert schema["info"]["version"]


def test_openapi_path_count(paths):
    assert len(paths) == 13, f"Expected 13 paths, got {len(paths)}: {sorted(paths)}"


# ── ApplicationListResponse envelope ──────────────────────────────────────────


def test_application_list_response_schema_exists(components):
    assert "ApplicationListResponse" in components


def test_application_list_response_has_items_and_pagination(components):
    props = components["ApplicationListResponse"].get("properties", {})
    assert "items" in props
    assert "total" in props
    assert "limit" in props
    assert "offset" in props


# ── GET /applications query params ────────────────────────────────────────────


def test_applications_list_has_new_query_params(paths):
    params = {p["name"] for p in paths["/api/v1/applications"]["get"].get("parameters", [])}
    assert "sort" in params, "sort param missing"
    assert "limit" in params, "limit param missing"
    assert "offset" in params, "offset param missing"
    assert "search" in params, "search param missing"
    assert "stage" in params, "stage param missing"


def test_applications_list_sort_param_has_enum(paths):
    params = paths["/api/v1/applications"]["get"].get("parameters", [])
    sort_param = next((p for p in params if p["name"] == "sort"), None)
    assert sort_param is not None
    schema = sort_param.get("schema", {})
    # FastAPI inlines Literal as allOf or enum depending on version
    enum_values = schema.get("enum") or schema.get("allOf", [{}])[0].get("enum", [])
    for expected in (
        "updated_at_desc", "updated_at_asc",
        "created_at_desc", "created_at_asc",
        "last_status_change_at_desc", "last_status_change_at_asc",
    ):
        assert expected in enum_values, f"Sort value missing: {expected}"


# ── ApplicationRead age fields ─────────────────────────────────────────────────


def test_application_read_has_age_fields(components):
    props = components["ApplicationRead"].get("properties", {})
    assert "days_in_pipeline" in props
    assert "days_since_applied" in props
    assert "days_in_current_status" in props


# ── Documents endpoints ────────────────────────────────────────────────────────


def test_application_documents_path_present(paths):
    assert "/api/v1/applications/{app_id}/documents" in paths


def test_application_documents_has_get_and_post(paths):
    ops = paths["/api/v1/applications/{app_id}/documents"]
    assert "get" in ops
    assert "post" in ops


def test_document_detail_path_present(paths):
    assert "/api/v1/documents/{document_id}" in paths


def test_document_detail_has_get_and_delete(paths):
    ops = paths["/api/v1/documents/{document_id}"]
    assert "get" in ops
    assert "delete" in ops
    assert "post" not in ops


def test_document_download_path_present(paths):
    assert "/api/v1/documents/{document_id}/download" in paths


def test_document_download_has_get_only(paths):
    ops = paths["/api/v1/documents/{document_id}/download"]
    assert "get" in ops
    assert "post" not in ops


def test_document_read_schema_exists(components):
    assert "DocumentRead" in components


def test_document_list_response_schema_exists(components):
    assert "DocumentListResponse" in components


def test_document_list_response_has_items_and_total(components):
    props = components["DocumentListResponse"].get("properties", {})
    assert "items" in props
    assert "total" in props


def test_document_read_has_required_fields(components):
    props = components["DocumentRead"].get("properties", {})
    for field in ("id", "application_id", "kind", "original_filename",
                  "content_type", "size_bytes", "sha256_hash", "status"):
        assert field in props, f"DocumentRead missing field: {field}"
