import {
  LOCATION_FRANKFURT,
  PLATFORM_INDEED,
  PLATFORM_LINKEDIN,
  PLATFORM_STEPSTONE,
} from "./seedDemoData.constants";
import type { DemoItemSeed } from "./seedDemoData.types";

export const DEMO_ITEM_SEEDS_SECONDARY: readonly DemoItemSeed[] = [
  {
    title: "Junior Fullstack (React/Node)",
    company: "DataDock",
    location: "Eschborn",
    platform: PLATFORM_INDEED,
    url: "https://example.com/jobs/datadock-jr-fs",
    description: "React + Node, basics of cloud and monitoring.",
  },
  {
    title: "Trainee Software Engineer",
    company: "AlphaBridge",
    location: LOCATION_FRANKFURT,
    platform: PLATFORM_STEPSTONE,
    url: "https://example.com/jobs/alphabridge-trainee-se",
    description: "Learning path, structured onboarding.",
  },
  {
    title: "Junior Frontend - Design System",
    company: "PixelPoint",
    location: "Darmstadt",
    platform: PLATFORM_LINKEDIN,
    url: "https://example.com/jobs/pixelpoint-jr-ds",
    description: "Storybook, reusable components, docs.",
  },
  {
    title: "Junior Developer (Web)",
    company: "FinLite",
    location: LOCATION_FRANKFURT,
    platform: PLATFORM_INDEED,
    url: "https://example.com/jobs/finlite-jr-web",
    description: "Fintech domain, clean code, security basics.",
  },
  {
    title: "Frontend Intern/Junior",
    company: "GreenStack",
    location: "Mainz",
    platform: PLATFORM_STEPSTONE,
    url: "https://example.com/jobs/greenstack-fe-intern",
    description: "Intern-to-junior pipeline, practical tasks.",
  },
  {
    title: "Junior Software Developer",
    company: "CodeCrafters",
    location: "Wiesbaden",
    platform: PLATFORM_LINKEDIN,
    url: "https://example.com/jobs/codecrafters-jr",
    description: "Pair programming, small increments.",
  },
  {
    title: "Junior Frontend (React) - Product",
    company: "Produktiv.io",
    location: LOCATION_FRANKFURT,
    platform: PLATFORM_INDEED,
    url: "https://example.com/jobs/produktiv-io-jr-fe",
    description: "Product team, analytics mindset, UI polish.",
  },
  {
    title: "Junior Web Dev - Hybrid",
    company: "MetroByte",
    location: "Darmstadt",
    platform: PLATFORM_STEPSTONE,
    url: "https://example.com/jobs/metrobyte-jr-hybrid",
    description: "Hybrid schedule, mentor, modern tooling.",
  },
  {
    title: "Junior Developer - Career Starter",
    company: "StartWerk",
    location: LOCATION_FRANKFURT,
    platform: PLATFORM_LINKEDIN,
    url: "https://example.com/jobs/startwerk-starter",
    description: "Career starter program, training + projects.",
  },
  {
    title: "Junior Frontend - React/TS",
    company: "MainRiver",
    location: "Offenbach",
    platform: PLATFORM_INDEED,
    url: "https://example.com/jobs/mainriver-jr-react-ts",
    description: "React/TS, tests, pragmatic engineering.",
  },
];
