import {
  LOCATION_FRANKFURT,
  PLATFORM_INDEED,
  PLATFORM_LINKEDIN,
  PLATFORM_STEPSTONE,
} from "./seedDemoData.constants";
import type { DemoItemSeed } from "./seedDemoData.types";

export const DEMO_ITEM_SEEDS_PRIMARY: readonly DemoItemSeed[] = [
  {
    title: "Junior Frontend Developer (React)",
    company: "NovaSoft GmbH",
    location: LOCATION_FRANKFURT,
    platform: PLATFORM_LINKEDIN,
    url: "https://example.com/jobs/novasoft-jr-fe",
    description: "React, TypeScript, UI components, testing basics.",
  },
  {
    title: "Trainee Web Developer",
    company: "MainCode AG",
    location: LOCATION_FRANKFURT,
    platform: PLATFORM_INDEED,
    url: "https://example.com/jobs/maincode-trainee-web",
    description: "HTML/CSS/JS, mentorship, small feature tasks.",
  },
  {
    title: "Junior Fullstack Developer",
    company: "RheinTech",
    location: "Wiesbaden",
    platform: PLATFORM_STEPSTONE,
    url: "https://example.com/jobs/rheintec-jr-fullstack",
    description: "Node.js + React, REST APIs, PostgreSQL.",
  },
  {
    title: "Frontend Developer (Entry)",
    company: "CloudWerk",
    location: "Darmstadt",
    platform: PLATFORM_LINKEDIN,
    url: "https://example.com/jobs/cloudwerk-fe-entry",
    description: "SPA, performance basics, accessibility awareness.",
  },
  {
    title: "Software Developer (Junior)",
    company: "ByteBahn",
    location: LOCATION_FRANKFURT,
    platform: PLATFORM_INDEED,
    url: "https://example.com/jobs/bytebahn-jr-dev",
    description: "Generalist role, agile team, CI/CD exposure.",
  },
  {
    title: "Junior UI Developer",
    company: "UXForge",
    location: "Offenbach",
    platform: PLATFORM_STEPSTONE,
    url: "https://example.com/jobs/uxforge-jr-ui",
    description: "Design systems, CSS, component libraries.",
  },
  {
    title: "Junior React Developer",
    company: "Komet Labs",
    location: "Mainz",
    platform: PLATFORM_LINKEDIN,
    url: "https://example.com/jobs/komet-jr-react",
    description: "React hooks, state management, API integration.",
  },
  {
    title: "Trainee Frontend (TypeScript)",
    company: "SpreeTech",
    location: "Remote (DE)",
    platform: PLATFORM_INDEED,
    url: "https://example.com/jobs/spreetech-trainee-ts",
    description: "Remote-friendly, TypeScript first, code reviews.",
  },
  {
    title: "Junior Web Engineer",
    company: "Horizon IT",
    location: LOCATION_FRANKFURT,
    platform: PLATFORM_STEPSTONE,
    url: "https://example.com/jobs/horizon-jr-web",
    description: "Web fundamentals + modern frameworks.",
  },
  {
    title: "Frontend Developer (Junior) - Hybrid",
    company: "Schnittstelle GmbH",
    location: LOCATION_FRANKFURT,
    platform: PLATFORM_LINKEDIN,
    url: "https://example.com/jobs/schnittstelle-jr-hybrid",
    description: "Hybrid, team collaboration, incremental delivery.",
  },
];
