export const LOOP_PLATFORM_IDS = [
  "linkedin",
  "indeed",
  "stepstone",
  "xing",
  "jobvector",
  "joblift",
  "kimeta",
  "meinestadt",
  "monster",
  "jobware",
  "gigajob",
  "jooble",
  "adzuna",
  "glassdoor",
  "germantechjobs",
  "honeypot",
  "instaffo",
  "wellfound",
  "getinit",
  "wearedevelopers",
  "devjobs",
  "arbeitnow",
  "remotive",
  "remoteok",
  "jobspresso",
  "eurojobs",
  "thelocal",
  "berlinstartupjobs",
  "arbeitgeber",
  "bundeswehr"
] as const;

export type LoopPlatform = (typeof LOOP_PLATFORM_IDS)[number];
